packages:
  - packages/*
  - playground/*
  - internal/*
  - docs

shellEmulator: true
verifyDepsBeforeRun: install
trustPolicy: no-downgrade

catalog:
  '@napi-rs/cli': ^3.5.0
  '@napi-rs/wasm-runtime': 1.1.0
