/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface DiffItem {
  path: string
  operation: string
  oldValue?: string
  newValue?: string
}

/** 计算两个JSON字符串的差异，直接返回差异对象数组 */
export declare function diffJson(oldJson: string, newJson: string): Array<DiffItem>
