/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 应用差异到JSON字符串 */
export declare function applyJsonDiff(jsonStr: string, diffOperations: string): string

/** 获取详细的JSON差异信息（用于前端可视化） */
export declare function getJsonDiffDetails(oldJson: string, newJson: string): string

/** 计算两个JSON字符串的差异 */
export declare function jsonDiff(oldJson: string, newJson: string): string

export declare function plus100(input: number): number
