import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

import type { ReleaseConfig } from '../../src/workspace/types'

import * as exec from '../../src/workspace/exec'
import {
  restorePackageChangelogs,
  runChangesetsFixedVersion,
  snapshotPackageChangelogs,
} from '../../src/workspace/changesets'

function createTempDir(): string {
  return mkdtempSync(join(tmpdir(), 'release-test-changesets-'))
}

function writePackageJson(dir: string, name: string, version = '0.0.0'): void {
  mkdirSync(dir, { recursive: true })

  writeFileSync(
    join(dir, 'package.json'),
    `${JSON.stringify(
      {
        name,
        version,
      },
      null,
      2,
    )}\n`,
  )
}

function makeReleaseConfig(dir: string): ReleaseConfig {
  return {
    repo: 'baicie/test',
    repositoryUrl: 'https://github.com/baicie/test.git',
    mode: 'changesets-fixed',
    cwd: dir,
    workspace: {
      roots: [join(dir, 'packages')],
    },
  }
}

function mockChangesetVersionFailure(): void {
  vi.spyOn(exec, 'run').mockImplementation(async command => {
    if (command === 'pnpm') {
      throw new Error('changeset version failed')
    }

    return {
      exitCode: 0,
      stdout: '',
      stderr: '',
    }
  })
}

describe('snapshotPackageChangelogs', () => {
  let dir: string

  beforeEach(() => {
    dir = createTempDir()

    writePackageJson(join(dir, 'packages', 'pkg-a'), '@test/pkg-a')
    writePackageJson(join(dir, 'packages', 'pkg-b'), '@test/pkg-b')
  })

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true })
    vi.restoreAllMocks()
  })

  it('records non-existent changelogs as existed: false', () => {
    const snapshot = snapshotPackageChangelogs(makeReleaseConfig(dir))

    expect(snapshot.size).toBe(2)

    for (const [, item] of snapshot) {
      expect(item.existed).toBe(false)
      expect(item.content).toBe('')
    }
  })

  it('records existing changelog content', () => {
    const fileA = join(dir, 'packages', 'pkg-a', 'CHANGELOG.md')
    const originalContent = '# Changelog\n\n- Some existing entry.'

    writeFileSync(fileA, originalContent)

    const snapshot = snapshotPackageChangelogs(makeReleaseConfig(dir))
    const found = Array.from(snapshot.entries()).find(([f]) =>
      f.endsWith('pkg-a/CHANGELOG.md'),
    )

    expect(found).toBeDefined()

    const [, item] = found!

    expect(item.existed).toBe(true)
    expect(item.content).toBe(originalContent)
  })
})

describe('restorePackageChangelogs', () => {
  let dir: string

  beforeEach(() => {
    dir = createTempDir()

    writePackageJson(join(dir, 'packages', 'pkg-a'), '@test/pkg-a')
    writePackageJson(join(dir, 'packages', 'pkg-b'), '@test/pkg-b')
  })

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true })
    vi.restoreAllMocks()
  })

  it('does not delete existing changelogs after cleanup', () => {
    const fileA = join(dir, 'packages', 'pkg-a', 'CHANGELOG.md')
    const originalContent = '# Changelog\n\n- Important historical entry.'

    writeFileSync(fileA, originalContent)

    const snapshot = snapshotPackageChangelogs(makeReleaseConfig(dir))

    writeFileSync(fileA, '# New content from changeset generation\n')
    expect(readFileSync(fileA, 'utf-8')).toContain('from changeset generation')

    restorePackageChangelogs(snapshot)

    expect(readFileSync(fileA, 'utf-8')).toBe(originalContent)
  })

  it('deletes newly created changelogs that did not exist before', () => {
    const fileA = join(dir, 'packages', 'pkg-a', 'CHANGELOG.md')

    const snapshot = snapshotPackageChangelogs(makeReleaseConfig(dir))

    expect(existsSync(fileA)).toBe(false)

    writeFileSync(fileA, '# Generated by changeset\n')

    restorePackageChangelogs(snapshot)

    expect(existsSync(fileA)).toBe(false)
  })

  it('restores multiple packages correctly', () => {
    const fileA = join(dir, 'packages', 'pkg-a', 'CHANGELOG.md')
    const fileB = join(dir, 'packages', 'pkg-b', 'CHANGELOG.md')
    const contentA = 'Content A'
    const contentB = 'Content B'

    writeFileSync(fileA, contentA)
    writeFileSync(fileB, contentB)

    const snapshot = snapshotPackageChangelogs(makeReleaseConfig(dir))

    writeFileSync(fileA, 'overwritten A')
    writeFileSync(fileB, 'overwritten B')

    restorePackageChangelogs(snapshot)

    expect(readFileSync(fileA, 'utf-8')).toBe(contentA)
    expect(readFileSync(fileB, 'utf-8')).toBe(contentB)
  })
})

describe('runChangesetsFixedVersion failure recovery', () => {
  let dir: string

  beforeEach(() => {
    dir = createTempDir()

    writePackageJson(join(dir, 'packages', 'pkg-a'), '@test/pkg-a')
    mkdirSync(join(dir, '.changeset'), { recursive: true })
  })

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true })
    vi.restoreAllMocks()
  })

  it('restores existing package changelog when changeset version fails', async () => {
    const fileA = join(dir, 'packages', 'pkg-a', 'CHANGELOG.md')
    const originalContent = '# Changelog\n\n- Important entry.'
    const config = makeReleaseConfig(dir)
    const afterVersion = vi.fn()

    writeFileSync(fileA, originalContent)

    mockChangesetVersionFailure()

    await expect(
      runChangesetsFixedVersion({ ...config, afterVersion }, '1.0.0'),
    ).rejects.toThrow('changeset version failed')

    expect(readFileSync(fileA, 'utf-8')).toBe(originalContent)
    expect(afterVersion).not.toHaveBeenCalled()
  })

  it('removes generated package changelog when changeset version fails', async () => {
    const fileA = join(dir, 'packages', 'pkg-a', 'CHANGELOG.md')
    const config = makeReleaseConfig(dir)

    mockChangesetVersionFailure()

    await expect(runChangesetsFixedVersion(config, '1.0.0')).rejects.toThrow(
      'changeset version failed',
    )

    expect(existsSync(fileA)).toBe(false)
  })

  it('removes synthetic changeset file even when flow fails', async () => {
    const config = makeReleaseConfig(dir)

    mockChangesetVersionFailure()

    await expect(runChangesetsFixedVersion(config, '1.0.0')).rejects.toThrow(
      'changeset version failed',
    )

    const syntheticFile = join(dir, '.changeset', 'release.md')

    expect(existsSync(syntheticFile)).toBe(false)
  })
})
