import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

import {
  restorePackageChangelogs,
  snapshotPackageChangelogs,
} from '../../src/workspace/changesets'
import type { ReleaseConfig } from '../../src/workspace/types'

function createTempDir(): string {
  const dir = join(tmpdir(), 'release-test-changesets-' + Date.now())
  mkdirSync(dir, { recursive: true })
  return dir
}

function makeReleaseConfig(dir: string): ReleaseConfig {
  return {
    repo: 'baicie/test',
    repositoryUrl: 'https://github.com/baicie/test.git',
    mode: 'workspace-fixed',
    cwd: dir,
    workspace: {
      roots: [join(dir, 'packages')],
    },
  }
}

describe('snapshotPackageChangelogs', () => {
  let dir: string

  beforeEach(() => {
    dir = createTempDir()
    mkdirSync(join(dir, 'packages', 'pkg-a'), { recursive: true })
    mkdirSync(join(dir, 'packages', 'pkg-b'), { recursive: true })
  })

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true })
  })

  it('records non-existent changelogs as existed: false', () => {
    const snapshot = snapshotPackageChangelogs(makeReleaseConfig(dir))
    expect(snapshot.size).toBeGreaterThanOrEqual(2)

    for (const [, item] of snapshot) {
      expect(item.existed).toBe(false)
      expect(item.content).toBe('')
    }
  })

  it('records existing changelog content', () => {
    const fileA = join(dir, 'packages', 'pkg-a', 'CHANGELOG.md')
    const originalContent = '# Changelog\n\n- Some existing entry.'
    writeFileSync(fileA, originalContent)

    const snapshot = snapshotPackageChangelogs(makeReleaseConfig(dir))
    const found = Array.from(snapshot.entries()).find(([f]) =>
      f.endsWith('pkg-a/CHANGELOG.md'),
    )

    expect(found).toBeDefined()
    const [, item] = found!
    expect(item.existed).toBe(true)
    expect(item.content).toBe(originalContent)
  })
})

describe('restorePackageChangelogs', () => {
  let dir: string

  beforeEach(() => {
    dir = createTempDir()
    mkdirSync(join(dir, 'packages', 'pkg-a'), { recursive: true })
    mkdirSync(join(dir, 'packages', 'pkg-b'), { recursive: true })
  })

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true })
  })

  it('does NOT delete existing changelogs after "cleanup"', () => {
    const fileA = join(dir, 'packages', 'pkg-a', 'CHANGELOG.md')
    const originalContent = '# Changelog\n\n- Important historical entry.'
    writeFileSync(fileA, originalContent)

    const snapshot = snapshotPackageChangelogs(makeReleaseConfig(dir))

    writeFileSync(fileA, '# New content from changeset generation\n')
    expect(readFileSync(fileA, 'utf-8')).toContain('from changeset generation')

    restorePackageChangelogs(snapshot)

    expect(readFileSync(fileA, 'utf-8')).toBe(originalContent)
  })

  it('deletes newly created changelogs that did not exist before', () => {
    const fileA = join(dir, 'packages', 'pkg-a', 'CHANGELOG.md')

    const snapshot = snapshotPackageChangelogs(makeReleaseConfig(dir))
    expect(existsSync(fileA)).toBe(false)

    writeFileSync(fileA, '# Generated by changeset\n')

    restorePackageChangelogs(snapshot)

    expect(existsSync(fileA)).toBe(false)
  })

  it('restores multiple packages correctly', () => {
    const fileA = join(dir, 'packages', 'pkg-a', 'CHANGELOG.md')
    const fileB = join(dir, 'packages', 'pkg-b', 'CHANGELOG.md')
    const contentA = 'Content A'
    const contentB = 'Content B'

    writeFileSync(fileA, contentA)
    writeFileSync(fileB, contentB)

    const snapshot = snapshotPackageChangelogs(makeReleaseConfig(dir))

    writeFileSync(fileA, 'overwritten A')
    writeFileSync(fileB, 'overwritten B')

    restorePackageChangelogs(snapshot)

    expect(readFileSync(fileA, 'utf-8')).toBe(contentA)
    expect(readFileSync(fileB, 'utf-8')).toBe(contentB)
  })
})
